version: '3'

services:
  db_postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - database_network
  django_app:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE='spaceag.settings'
    command: pytest
    volumes:
      - .:/code
      - static:/code/static
    networks:
      - database_network
      - nginx_network
    depends_on:
      - db_postgres
  nginx_django:
    image: nginx:1.13
    ports:
      - 80:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/code/static
    networks:
      - nginx_network
    depends_on:
      - django_app
networks:
  nginx_network:
    driver: bridge
  database_network:
    driver: bridge
volumes:
  .:
  postgres_data:
  static: